name: "publish"

on:
  push:
    branches:
      - release

# Esse workflow cria ou atualiza um release com os artefatos gerados a partir do submódulo "ahri-app".

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Builds Desktop
          - platform: "macos-latest" # Desktop para Arm (M1)
            args: "--target aarch64-apple-darwin"
            mobile: false
          - platform: "macos-latest" # Desktop para Intel
            args: "--target x86_64-apple-darwin"
            mobile: false
          - platform: "ubuntu-22.04" # Desktop para Linux
            args: ""
            mobile: false
          - platform: "windows-latest" # Desktop para Windows
            args: ""
            mobile: false
          # Builds Mobile
          - platform: "macos-latest" # Build mobile para iOS (somente em macOS)
            args: ""
            mobile: true
          - platform: "ubuntu-22.04" # Build mobile para Android (em Ubuntu, por exemplo)
            args: ""
            mobile: true

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AHRI_BUILD }}
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      # Instala o Android NDK somente para builds mobile no Ubuntu (Android)
      - name: Install Android NDK
        if: ${{ matrix.mobile && matrix.platform == 'ubuntu-22.04' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y android-ndk
          # Define NDK_HOME com base no local do ndk-build
          echo "NDK_HOME=$(dirname $(which ndk-build))/.." >> $GITHUB_ENV

      - name: Install frontend dependencies
        working-directory: ahri-app
        run: yarn install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@mobile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "ahri-app"
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          mobile: ${{ matrix.mobile }}
          args: ${{ matrix.args }}
